### ISSUE TITLE
Read a Json file and plot it? 

### ISSUE THREAD

**Issue by Peterpunk19** [rawgraphs/rawgraphs-app#100]
I want to plot the exported file as json

**Comment by almet** [comment]
I had the expectation that JSON files would also be readable by Raw, and was surprised it wasn't the case! that would be a useful addition I believe, but then you would need to remove the hierarchical data, which might cause trouble sometimes.

**Comment by danielsu** [comment]
Importing JSON and handle hierachical datastructure - this is exactly why i forked this nice project.
To workaround cross-origin-resource from browser security, i needed to add a proxy server. All contained in build files.
I've come to a working beta status. Updated documentation and video tutorial will follow soon.

Maybe check out and leave a comment.
https://github.com/danielsu/raw

**Comment by mikima** [comment]
@almet we thought about it but since the whole app is based on tabular data, it was too complex to reduce json to such format.
Anyway with [version 1.2.0](v1.2.0) is now possibile to load arrays of objects from json as tables.

**Comment by danielsu** [comment]
@mikima interesting side note: I forked the project in December last year and it had version 1.0.0 from 2014. Now there are a lot of changes online, coming from commits through out the last years ;-) I'm looking forward to having a look at your v1.2 :-)

**Comment by danielsu** [comment]
> we thought about it but since the whole app is based on tabular data, it was too complex to reduce json to such format.
@mikima : I updated the documentation, images and added a youtube video demo on my extension for nested JSON transformation for table like representation. Maybe you can leave a though on this. See [forked repo](https://github.com/danielsu/raw) and [video demo](https://www.youtube.com/watch?v=bgkKO4IwE54)

**Comment by danielsu** [comment]
@mikima and @giorgiocaviglia 
Are you generally interested in supporting nested JSON data?
I've extracted my coded logic into a separate [ds-angular-nested-json-to-table](https://github.com/danielsu/ds-angular-nested-json-to-table) repo, providing an easy to use angular service. If you are interested, I'm going to fork your new v1.2 and build in this feature the next few weeks. Please leave a reply.

**Comment by mikima** [comment]
@danielsu thanks for your effort, but we are not planning to add support for nested json file in the short period. We can keep it in consideration for the next major release, we will keep you posted! It's indeed a good idea to abstract the logic and make it as angular service.
