### ISSUE TITLE
Set chart options with key instead of integers

### ISSUE THREAD

**Issue by llazzaro** [rawgraphs/rawgraphs-app#116]
Hello,

I found I little difficult to change the color scale and other options of the chart.
I'm currently using 

> chart.options()[4].value

 to change the color scale.
To solve the issue I think the best is to use keys to access options like:

> chart.options()['Color scale']

To detect the index I'm using the title() to translate it to the index of the option.

If you think this could be added to the project, let me know and I can try to do a pull request.
Since some code is already using indexes, this should be backwars compatible (accept index and keys)

**Comment by uf0** [comment]
Hi @llazzaro, yes you are right!

We are thinking to move Raw to a _proper_ library and, for sure, you suggestion goes in that direction.
As of now, we don't have any specific deadline but you can start to submit your pull request.

**Comment by uf0** [comment]
Hi, we released the documentation for the new rawgraphs-core and charts library:
https://rawgraphs.io/rawgraphs-core/docs/api
