### ISSUE TITLE
labels wrapping + font

### ISSUE THREAD

**Issue by ikashnitsky** [rawgraphs/rawgraphs-app#119]
I've been trying RAW to produce a treemap, replicating the one that I producer with R for my [recent blog post](https://ikashnitsky.github.io/2017/dd-journals-frequency/).
![r](https://ikashnitsky.github.io/images/170214/treemap-dd-stats.png)
Data - [dd-stats.csv](https://ikashnitsky.github.io/doc/misc/dd-stats/dd-stats.csv)
***
## The output of RAW looks like this
![raw](https://habrastorage.org/files/99b/908/d48/99b908d48752463b84d78ea56b898840.PNG)
***
It would be nice to have labels nicely wrapped within the rectangles.
Also, even a basic choice of fonts would be much appreciated.

**Comment by boogheta** [comment]
Well, as the name says: raw produces... "raw" dataviz as svg, so that they can then be tuned into any tool you like, so not sure it would be appropriate :)

**Comment by ikashnitsky** [comment]
I thought, the whole idea was to provide an easy tool to produce modern types of viz without hardcore coding skills. If so, it makes sense to have a fine output rather then a raw version for further modifications using graphical editors.

**Comment by uf0** [comment]
in v2 we added more controls on labels. 
No plan to add wrapping option as of now
