### ISSUE TITLE
Execution of JS in data files

### ISSUE THREAD

**Issue by hg77** [rawgraphs/rawgraphs-app#121]
I'm not sure if it is a bug or a feature.

If you pass some url of a javascript file it will get executed in the context of the website.
E.g. if you save the file data.tsv:
```js
alert(window.location);
```
You'll get the alert box on import from url http://urlto/data.tsv. This may be a security problem if you embed raw in a bigger context, i.e. an intranet.

**Comment by mikima** [comment]
not able to reproduce it

**Comment by hg77** [comment]
Thanks for looking into this.
I can still reproduce it.

Run on server:
$ cd rawgraphics
$ git rev-parse HEAD
29272a58d2497548364508b4aa6e1da392e8530c
$ echo "alert(window.location);" > data.tsv
$ python -m SimpleHTTPServer 9999 # assume it's myserver

In Browser:
1. Point Browser (FF 61.0.1 (64-bit) or Chrome 67.0.3396.99 (Official Build) (64-bit) both on windows) to myserver:9999.
2. Click "From URL"
3. Copy and paste "http://myserver:9999/data.tsv" into URL field. The leading http:// is important. Without it you get "Whoops! Something wrong with the URL you provided."
4. Notice the alert popup.

What happens for you?
