### ISSUE TITLE
boxplot chart issue with y axis en long number

### ISSUE THREAD

**Issue by llazzaro** [rawgraphs/rawgraphs-app#129]
If boxplot has number like 1,000 it has render problems with the default Margin of 20.

example:
<img width="64" alt="screen shot 2017-04-11 at 9 16 45 pm" src="https://cloud.githubusercontent.com/assets/568181/24936216/c145a06c-1efd-11e7-87b7-16f0691379e1.png">

**Comment by llazzaro** [comment]
My fix solves this changing the default margin to 30.
<img width="75" alt="screen shot 2017-04-11 at 9 16 24 pm" src="https://cloud.githubusercontent.com/assets/568181/24936232/e4e7fdb2-1efd-11e7-9001-5d4b9a30bd66.png">

**Comment by llazzaro** [comment]
https://github.com/densitydesign/raw/pull/130

**Comment by mikima** [comment]
Still we need to find a consistent solution to move labels according to their size.

**Comment by Gjum** [comment]
An acceptable solution might be to use SI units: 1K, 10K, 100K/0.1M, 1M etc.

These are limited in width, and at such big numbers showing the least significant digits on an axis is rather pointless.

**Comment by uf0** [comment]
no plan to add automatic margins based on axis label, also in v2 you should play with margins option
