### ISSUE TITLE
Add support for specifying URL to load in URL

### ISSUE THREAD

**Issue by lucaswerkmeister** [rawgraphs/rawgraphs-app#140]
It would be cool if you could specify a URL to load via http://app.rawgraphs.io/?url=URL, e. g. [like this](http://app.rawgraphs.io/?url=https:%2F%2Fquery.wikidata.org%2Fbigdata%2Fnamespace%2Fwdq%2Fsparql%3Fquery%3D%2523Overall%2520causes%2520of%2520death%2520ranking%250A%2523added%2520before%25202016-10%250A%250A%2523defaultView%253ABubbleChart%250A%2523TEMPLATE%253D%257B%2522template%2522%253A%2522Overall%2520causes%2520of%2520death%2520ranking%2520of%2520%253Fthing%2520%2522%252C%2522variables%2522%253A%257B%2522%253Fthing%2522%253A%2520%257B%2522query%2522%253A%2522SELECT%2520%253Fid%2520%2520(COUNT(%253Fid)%2520AS%2520%253Fcount)%2520WHERE%2520%257B%2520%2520%253Fsub%2520wdt%253AP509%2520%253Fy.%2520%2520%253Fsub%2520wdt%253AP31%2520%253Fid.%2520%257D%2520GROUP%2520BY%2520%253Fid%2520%2522%257D%2520%257D%2520%257D%250ASELECT%2520%253Fcid%2520%253Fcause%2520(COUNT(*)%2520AS%2520%253Fcount)%2520WHERE%2520%257B%250A%2520%2520BIND(wd%253AQ5%2520AS%2520%253Fthing)%250A%2520%2520%253Fpid%2520wdt%253AP31%2520%253Fthing.%250A%2520%2520%253Fpid%2520wdt%253AP509%2520%253Fcid.%250A%2520%2520OPTIONAL%2520%257B%250A%2520%2520%2520%2520%253Fcid%2520rdfs%253Alabel%2520%253Fcause.%250A%2520%2520%2520%2520FILTER((LANG(%253Fcause))%2520%253D%2520%2522en%2522)%250A%2520%2520%257D%250A%257D%250AGROUP%2520BY%2520%253Fcid%2520%253Fcause%250AORDER%2520BY%2520DESC(%253Fcount)%2520%253Fcause). This feature was showcased in [this tweet](https://twitter.com/rawgraphs/status/867758057429884930), and Wikidata Query Service support is pending in [this change](https://gerrit.wikimedia.org/r/#/c/355593/), but this doesn’t yet seem to be available on the main website, and I couldn’t find any commits, issues or pull requests related to it.

**Comment by poVoq** [comment]
cool would be also Odata support

**Comment by ysykzheng** [comment]
please see #176
