### ISSUE TITLE
The header of the table view is not displayed on Firefox

### ISSUE THREAD

**Issue by giorgiouboldi** [rawgraphs/rawgraphs-app#147]
Firefox version 56.0.1

**Comment by msampathkumar** [comment]
@giorgiouboldi in firefox(57.0.4), it not just table header but also first 12 rows are hidden for 'Movies' data(provided in `try our sample` option). It looks like is data available but in terms of UI view, they are not visible.

**Comment by mikima** [comment]
Probably fixed with cc379fad326b3e5997db1b2ef5753a64d17892ea, to be checked.
