### ISSUE TITLE
The demo on the website does not allow JSON data to process.

### ISSUE THREAD

**Issue by ubaidsworld** [rawgraphs/rawgraphs-app#149]
I have tried the demo on your website. The demo is not able to process my json output of the API response. I have read the thread from the issues and found this: https://github.com/danielsu/raw. 
If the above repository is included then why the demo is able to process the data?
Kindly let me know what is the  reason?

**Comment by msampathkumar** [comment]
@ubaidsworld I was testing json/csv data api's from from [Data Source](https://data.nasa.gov/Space-Science/Meteorite-Landings/gh4g-9sfh ). It seems to be working fine.

Only difference between csv & json API is that, after data is loaded from JSON API, we need select the data in '[' and ']' in UI. Web page show it as `Please select the array [ ] containing the records you want to load from the JSON above.`
