### ISSUE TITLE
Including editor in 3rd party libs

### ISSUE THREAD

**Issue by LaurensRietveld** [rawgraphs/rawgraphs-app#154]
I like rawgraphs, and would like to use it in one of my libraries (see https://yasgui.org or https://github.com/OpenTriply/YASGUI.server).
For this to work, I'd expect a simple initialization command where i can bin rawgraphs to a particular div, and add some csv data to the rawgraphs instance. 
I'm having trouble with the documentation though, as this mainly focuses on using rawgraphs as an end user, or adding other types of charts. 
So, is the scenario I described above feasible, and could you recommend some online resources (e.g. Other demos or places where rawgraphs is included) I can take a look at?

**Comment by uf0** [comment]
in the next weeks we will release the new `rawgraphs-core` library which can be used separately form the interface app
