### ISSUE TITLE
Color scale doesn't reset when changing chart

### ISSUE THREAD

**Issue by Mitch90** [rawgraphs/rawgraphs-app#170]
Case example: I pick a dataset and choose a scatterplot and for some reason change the color scale from ordinal to linear. If I now pick a different visual model, let's say a Gantt chart, the scale will remember my last choice and start as linear.

**Comment by Mitch90** [comment]
A possible enhancement: when creating the chart, there could be a check for the variable type in the color box. If number the chart calls for the linear scale, if string for an ordinal an so on.

**Comment by uf0** [comment]
now fixed in v2
