### ISSUE TITLE
Streamgraph: Date field only works with strict dates

### ISSUE THREAD

**Issue by Mitch90** [rawgraphs/rawgraphs-app#173]
The date field only works if it parses dates (it doesn't create the visualization with numbers as it used to)
Moreover, only a few dates are now supported compared from the previous version:
<img width="281" alt="screen shot 2018-06-26 at 15 46 43" src="https://user-images.githubusercontent.com/7771123/41916366-2e164f74-7958-11e8-8eeb-b73e50ee98a7.png">

**Comment by uf0** [comment]
in v2 now works also with numbers, accepted date format are the following

![Screenshot 2021-02-23 at 14 32 16](https://user-images.githubusercontent.com/1922342/108851138-66a4c600-75e4-11eb-90ec-31c8534ca584.png)
