### ISSUE TITLE
Project Save / Load functionailty

### ISSUE THREAD

**Issue by michaelmruta** [rawgraphs/rawgraphs-app#177]
Is there a proper way on how to get the state of the application as JSON object.

**Comment by stej** [comment]
Looked through the source code and I'm afraid there is none. It quite heavily uses angular, scopes, drag/drop via jquery-ui etc that I'm in doubts it's possible.

**Comment by zsilverzweig** [comment]
Agree, any kind of simple retention of settings would be amazing.

**Comment by mikima** [comment]
Hi all,
saving/loading settings is one of the goal of our fundraising campaign, have a look here:

https://igg.me/at/rawgraphs2

If we manage to reach the goal, it will be one of the functions (among many others) that will be added.

**Comment by uf0** [comment]
now supported in v2
