### ISSUE TITLE
alluvial diagram broken

### ISSUE THREAD

**Issue by kuczera** [rawgraphs/rawgraphs-app#179]
Given this set of data: 
http://dhd2016.digitale-akademie.de/workshop/data/epidat/csv/symbole_priesterhaende.txt
and choosing the alluvial diagram with the following order of steps:
Symbol
Address
Gender 
Timestamp

the visualization is broken.
![bildschirmfoto vom 2018-11-08 09-12-14](https://user-images.githubusercontent.com/10571362/48185810-82fa9700-e336-11e8-8fdf-c72e28161a83.png)

With v. 12. it works.
![bildschirmfoto vom 2018-11-08 09-12-40](https://user-images.githubusercontent.com/10571362/48185816-87bf4b00-e336-11e8-960e-8f293df5ac7c.png)

**Comment by uf0** [comment]
it should works in v2, try to increase `width` and `height` option
