### ISSUE TITLE
proposal: migrate from bower to yarn / webpack

### ISSUE THREAD

**Issue by shaunc** [rawgraphs/rawgraphs-app#182]
I haven't used bower for a number of years; checking out their site, I now see: "...psst! While Bower is maintained, we recommend using Yarn and Webpack or Parcel for front-end projects read how to migrate!"

If this project is meant to be viable going forward, I propose migrating from bower to npm or yarn and webpack.

This would certainly support the main use case. I am interested in incorporating as a library, and the current lack of a package.json means I need to hard-fork, which is unfortunate.

**Comment by stej** [comment]
Even when installing, there is a warning:

```
[51]: npm install -g bower
npm WARN deprecated bower@1.8.8: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
```

**Comment by uf0** [comment]
moved to `yarn` in v2
