### ISSUE TITLE
Alluvial diagram and gradient color

### ISSUE THREAD

**Issue by xcaeag** [rawgraphs/rawgraphs-app#186]
If it interests you, I have a rather simple piece of code that draws the links in color gradient.

Another adds the names of the different steps in the boxes.
If you wish, I can do a PR. Initial working is not changed, two parameters have been added.

![alluvial-2](https://user-images.githubusercontent.com/7790344/52414940-f81c6a80-2ae5-11e9-8f1a-bc7d9e4363d7.png)

![alluvial-3](https://user-images.githubusercontent.com/7790344/52414958-04082c80-2ae6-11e9-87f9-1d0c3b5da148.png)

**Comment by Sigfried** [comment]
@xcaeag, this looks like what I'm trying to do. I'm just looking for something to use for making a single diagram. Too bad no one ever responded (as far as I can tell) to your PR offer. I did find your fork at https://github.com/xcaeag/raw. I haven't tried it. I haven't used  rawgraphs either. So I have no idea how much of a time sink I'll be getting myself into. But thanks! And thanks, rawgraphs team, for all the work you did. It appears to me that there's probably still a need for it.
