### ISSUE TITLE
Quicker way how to setup all the variables?

### ISSUE THREAD

**Issue by stej** [rawgraphs/rawgraphs-app#187]
I have a file that is reguarly updated so that new data are supplied. I from time to time take this file, upload it to `raw`, manually select graph type, all the dimensions and also width, height, radius on the chart options itselft. 
This is quite time consuming and prevents me from me automating the process. 
It would be great that such metadata would be stored somewhere...

Also what came on my mind - if the definition was part of the input file, it might be parsed and used. 

Besides that I like `raw` a lot thank you for your effort!

**Comment by uf0** [comment]
in v2 you can now export/import the project
