### ISSUE TITLE
Add support for loading data from SPARQL 

### ISSUE THREAD

**Issue by ktk** [rawgraphs/rawgraphs-app#190]
I would like to be able to execute a SPARQL query to a SPARQL endpoint directly from RAWGraph. 

I propose to add the ability to select SPARQL as source here:

![rawgraph](https://user-images.githubusercontent.com/583021/57458213-3d7d3f00-7271-11e9-85e0-23d893a81313.jpg)

Minimal features needed:
* Input field for SPARQL endpoint
* Input field for SPARQL query (ideally with SPARQL syntax highlighting enabled)
* Optional: A way to provide a user/pw for the SPARQL endpoint

We created the library [d3-sparql](https://www.npmjs.com/package/d3-sparql), which returns a JSON object oriented at what d3-csv is doing. It is properly converting [RDF literal data types](https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal) to native JavaScript types. I think this would be a great starting point for implementing it.

We would be happy to help on that but I would need some pointers about where in the source code we would have to add that to get an idea of the complexity.

This is related to #189, which simply seems to pass a SPARQL query string.

**Comment by giorgiouboldi** [comment]
Thanks for opening the issue. In this phase we are planning further developments of the tool. 
Keep an eye on further updates.

**Comment by ktk** [comment]
Ok great, please let me know if we can contribute in any way.

**Comment by lklic** [comment]
Hello,

Any updates on when this will be integrated? I can't find any documentation in any of the recent releases.

Thanks!

**Comment by ktk** [comment]
@lklic it's WIP, we just had a call with the RAWgraphs team last week. First version should show up soon.
