### ISSUE TITLE
Work flow change - link samples to chart types

### ISSUE THREAD

**Issue by kirancheema** [rawgraphs/rawgraphs-app#196]
Hi Guys 

I've been circulating rawcharts to colleagues who haven't any experience with d3 or data vis before and while they like the capabilities they found it difficult to get started, and have feedback the following:

When new people start using rawcharts, It is difficult to know which example data sets work well with which charts,  you seem to need to know the data structures for the charts before you start, which make it difficult for people who are new to get started.

The workflow at the moment is Select Example Data / add your own -> Select chart type -> Configure 

Maybe swap around to Select Chart Type -> Add Data / Select Example Data -> Configure 

This would mean that you can then show the sample data sets that work best for a selected Viz - and even maybe have a default config for the data so that it shows an output sooner..

**Comment by uf0** [comment]
In v2 we added the suggested visual models to each datasets sample
