### ISSUE TITLE
Automation of chart creation in RAWGraphs

### ISSUE THREAD

**Issue by PawandeepKaur** [rawgraphs/rawgraphs-app#201]
Automate graph creation

Hello, 

For my project, I would like to automate the process of graph creation. 

Currently, raw takes the data and ask the user to make two decisions:
1) Select chart
2) Map the variables

I would like to automate these two steps. My algorithm will be choosing the appropriate chart type and variables.

So in this way, I would like to change the workflow of raw a bit. Can someone guide how to do that.? What files needs to be changed?

So far what I understood is controller.js gets the user input and triggers the raw.js to provide a suitable model. This then calls to the model and model dimension function, which further connects to the appropriate chart script. Then somehow it connects with directive.js. I could not understand completely what is the role of directives.js?

For this work, I really need to understand the raw at the deepest level. Can someone provide guidance to that?

Thanks

**Comment by uf0** [comment]
In the new version you can export/import project.
Plus in the next weeks we will release the new `rawgraphs-core` library so you can use it in your application
