### ISSUE TITLE
Drop NA

### ISSUE THREAD

**Issue by acbelisle** [rawgraphs/rawgraphs-app#202]
Hi, 
 I am trying to make an alluvial diagram to show my data. Everything works fine except for the "No data",  which are numerous in my data frame. I've tried to mark them as "NA" but they were treated as factors just as other variables. I also  tried to leave empty cells but they were converted to 0.
Is their any notation or option that would lead to drop them (equivalent of a drop.na in R) ? 
Thanks in advance for your help and for developing such a powerful and user friendly data visualization tool. 
Annie Claude

**Comment by uf0** [comment]
No filtering options are available, you should remove them from your original datasets
