### ISSUE TITLE
Line graph?

### ISSUE THREAD

**Issue by ColinMaudry** [rawgraphs/rawgraphs-app#204]
Hello,

I find this tool amazing, but I'm a bit a bit puzzled to see complex charts, but not the possibility to draw a line graph, an area graph, or a stack area graph.

https://datavizcatalogue.com/methods/line_graph.html
https://datavizcatalogue.com/methods/area_graph.html
https://datavizcatalogue.com/methods/stacked_area_graph.html

Is there a reason why you have not implemented them? I see pies and bar were added with #97.

Great job nonetheless :)

**Comment by uf0** [comment]
now available in v2
