### ISSUE TITLE
Alternatives?

### ISSUE THREAD

**Issue by exetico** [rawgraphs/rawgraphs-app#211]
Hi,

Is there any alterantives to RAWGraphs, where it's more or less "Dump the data, and show it"? I like the focus and the solution itself, but I'm just looking for alternatives like RAWGraphs, cause the codebase is getting a bit old, and the last release was in 2018 :-) 

I hope it's okay to ask here - I guess you guys have a good view of the alternatives, which are much like RAWGraphs. (_By searching, I'm primary finding alternatives with many options, but with a much larger feature-set. I like that RAWGraphs is very simple - I've other tools for complex calculations and so_)

**Comment by albertoxamin** [comment]
You could try https://visuafy.com/

**Comment by exetico** [comment]
It needs to be self-hosted :-) But thanks for the input!

**Comment by uf0** [comment]
try the new version released today
