### ISSUE TITLE
Cannot upload csv or tsv file.

### ISSUE THREAD

**Issue by soliverc** [rawgraphs/rawgraphs-app#213]
I've tried two file types now. 

It's transaction data and looks like this:

| date  | shop | amount |
| ------------- | ------------- | ------------- |
| 1/12/1985  | KFC  | 50  |
|1/12/1955  | mcondalds | 20  |

When I click "upload data" and select my file, nothing happens. 

The file is 300mb in size. Is this the problem? Is it too large? I tried copying the data but the web browser crashes.

**Comment by uf0** [comment]
The application is client side so yes 300mb could be too much.

try the new version released today
