### ISSUE TITLE
Request: variable-width bar chart / "histogram"

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [rawgraphs/rawgraphs-app#216]
I'm trying to graph the [election margin prediction market state](https://www.predictit.org/markets/detail/6653/What-will-be-the-Electoral-College-margin-in-the-2020-presidential-election); I've munged the data down to the following:

```csv
-538, -280,    11, 12, 11, 11, 12
-279, -210,    12, 13, 12, 12, 13
-209, -150,    18, 19, 18, 18, 19
-149, -100,    13, 14, 13, 13, 14
-99,  -60,     6,  7,  6,  6,  7
-59,  -30,     5,  5,  4,  4,  5
-29,  -10,     4,  4,  3,  3,  4
-9,   -1,      2,  3,  2,  2,  3
0,    9,       3,  4,  3,  3,  4
10,   29,      6,  6,  5,  5,  6
30,   59,      10, 10, 9,  9,  10
60,   99,      12, 12, 11, 11, 12
100,  149,     10, 10, 9,  9,  10
150,  209,     5,  6,  5,  5,  6
210,  279,     2,  3,  2,  2,  3
280,  538,     4,  5,  4,  4,  5
```

However, I don't see variable-width bar chart graphing as an option.

Could that be added?

Thank you.

**Comment by mikima** [comment]
I know this issue is quite old, but it should be possible with the new RAWGraphs 2.

Please let us know if the issue is solved.
