### ISSUE TITLE
Where can I find source code of direct dependencies?

### ISSUE THREAD

**Issue by jenkin** [rawgraphs/rawgraphs-app#219]
At the moment, I can't find repositories on Github for [@rawgraphs/rawgraphs-charts](https://www.npmjs.com/package/@rawgraphs/rawgraphs-charts) and [@rawgraphs/rawgraphs-core](https://www.npmjs.com/package/@rawgraphs/rawgraphs-core) packages. I missed something?

**Comment by uf0** [comment]
Hi, 

we are preparing the documentation for both packages and we will make them public in the next weeks.

**Comment by uf0** [comment]
Hi, 

yesterday we went public with the 2 repos and the documentation:

- https://github.com/rawgraphs/rawgraphs-charts/
- https://github.com/rawgraphs/rawgraphs-core/
- https://rawgraphs.io/rawgraphs-core/docs/
