### ISSUE TITLE
Bump react-color when unbugged

### ISSUE THREAD

**Issue by gffuma** [rawgraphs/rawgraphs-app#231]
Bump react-color when unbugged.
For now we rely on  `v2.17.3`

See:
https://github.com/casesandberg/react-color/issues/754

**Comment by mikima** [comment]
@gffuma is this still open?

**Comment by gffuma** [comment]
Yess i try to install it and the latest version of `react-color` still bugged :sweat_smile:

**Comment by bianchimro** [comment]
hey @gffuma 
seems like it has been fixed here:
https://github.com/casesandberg/react-color/pull/791

should we bump ?
