### ISSUE TITLE
Tutorial link nonexistent

### ISSUE THREAD

**Issue by aarontheman** [rawgraphs/rawgraphs-app#238]
Chose the 'line graph' type. Thumbnail of graph has no live links for 'code' or 'tutorial'.  (Contextual help for each area of drag and drop would be great too. Oh, and a user guide! Happy to help with all of this if someone teaches me how to use this beast.)

**Comment by uf0** [comment]
Documentation, examples and tutorials are on the way. Please check the main website for more information 

-> https://rawgraphs.io/

**Comment by aarontheman** [comment]
Good to hear, thanks!  In the meantime can you tell me how to make a
line graph like the one attached?
