### ISSUE TITLE
Legend colour, legend header tags, graph label font size

### ISSUE THREAD

**Issue by avfac** [rawgraphs/rawgraphs-app#239]
**In which part of the interface would this feature applies?**

[ ] 1. Load your data
[ ] 2. Choose a chart
[ ] 3. Mapping
[x ] 4. Customize
[ ] 5. Export

**Is your feature request related to a problem? Please describe.**
Thanks so much for the new version, much anticipated. However, I am not able to use the exported graph due to: (i) legend background is black (ii) legend headers include tags such as [csvdistinct] or [sum] (iii) cannot adjust the font size of labels, which is one of the features I was particularly looking forward to with the new release. 

**Describe the solution you'd like**
For the legend background colour to be the same as the chart background colour, and without the line that separates it.
For the tags in the legend headers to be removed or optional
For the size of the labels to be customizable

**Describe alternatives you've considered**
Mentioned above

**Additional context**
<img width="522" alt="Screenshot 2021-02-24 at 13 03 52" src="https://user-images.githubusercontent.com/79583582/109006221-bea20200-76a2-11eb-89a0-012df51bfa08.png">

**Comment by mikima** [comment]
Fixed with commit cedd6ec1767a29d88f6dfa9aade0769300f1e439
