### ISSUE TITLE
Alluvial - Horizontal adjustment of individual columns

### ISSUE THREAD

**Issue by Sindreo** [rawgraphs/rawgraphs-app#240]
**In which part of the interface would this feature applies?**

[ ] 1. Load your data
[ ] 2. Choose a chart
[ ] 3. Mapping
[x ] 4. Customize
[ ] 5. Export

**Is your feature request related to a problem? Please describe.**
When observations in an alluvial diagram has long names, the text of several columns might overlap. This is especially frustrating when there is i.e. only one column that have long observation names, as this will create overlapping issues with nearby columns, while other colums might have a ton of free space. 

**Describe the solution you'd like**
Possibility to adjust the horizontal position of individual columns, either by entering the margin manually, or by dragging (preferred).

**Describe alternatives you've considered**
Repel text so that long text is placed somewhere that does not cause overlap. In addition, it could be nice to have an option to decide which side of the bars the text should be for each individual column,

**Additional context**
Here, being able to adjust individual columns horizontally would allow for better utilization of the space. The leftmost and rightmost colums could be pushed more closely together, allowing the middle column with the long observation names to not overlap with the nearby column.
![issue](https://user-images.githubusercontent.com/79587079/109015350-53adf680-76b5-11eb-883c-c1e4d0ed15f8.png)

**Comment by mikima** [comment]
Hi, short answer, this is not possible with the current architecture, but you can manually fix it with any vector editor (Inkscape, Adobe Illustrator, Vectr, Microsoft Powerpoint, etc)

Long answer:
it's possible to add this kind of interaction to the chart, but not to export it when you save the .rawgraphs project file. This means that if you change the position, save the project and load it again you will lose the information.
For this reason we won't add this kind of options in the near future.
