### ISSUE TITLE
Missing labels in SVG graph file (Treemap diagram)

### ISSUE THREAD

**Issue by cmalat01** [rawgraphs/rawgraphs-app#241]
- Treemap diagram

**RAWGraphs Version**
2.0 Beta

**Web browser and version**
Firefox 85.0

**Operating System**
Mac Os Catalina 10.15.7

**Steps to reproduce this**
I produced a Treemap graph, looking great on Firefox, and exported the  svg file
When opening the SVG with GIMP 2.10, all labels are missing

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/79660454/109197417-f5434f80-776a-11eb-9603-69c883ccf6ec.png">

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/79660454/109197482-09874c80-776b-11eb-8b94-f254bda26b5c.png">

**Comment by mikima** [comment]
Can you upload the svg file? thanks!

**Comment by cmalat01** [comment]
it seems that I cannot upload svg files here (?)
let me see if I can send you an email

**Comment by cmalat01** [comment]
Here is the file

**Comment by mikima** [comment]
i don't think you can upload it here, you can use cloud services and share and url, thanks

**Comment by uf0** [comment]
Hi, 

if you want to edit the `.svg` file I strongly recommend to use a vector graphics software like [InkScape](https://inkscape.org/).

GIMP is primarily meant to edit raster image formats so you should download the `.png` or `.jpg` format instead.

<img width="580" alt="Screenshot 2021-02-26 at 09 57 15" src="https://user-images.githubusercontent.com/1922342/109278632-06e33080-7819-11eb-8ea8-4b3011e27c80.png">

**Comment by cmalat01** [comment]
You're right, my mistake... I opened the file with Inkscape: perfect.
Sorry for the trouble
Keep up the good job at RawGraphs: Love it!
