### ISSUE TITLE
Possibility to copy data

### ISSUE THREAD

**Issue by CRC-PSV** [rawgraphs/rawgraphs-app#242]
[X ] 1. Load your data
[ ] 2. Choose a chart
[ ] 3. Mapping
[ ] 4. Customize
[ X] 5. Export

**Is your feature request related to a problem? Please describe.**
In the previous version, it was possible to copy data table from excel, paste it into Rawgraphs, stack it, then copy from Rawgraphs the stacked data and paste it back in excel (for further use or modifications).
With version 2.0, there appears to be no possibility to select the stacked data in Rawgraphs to copy it.

**Describe the solution you'd like**
I'd like to be able to select and copy the data that is visible in Rawgraphs (typically once it has been stacked)

**Comment by cmalat01** [comment]
download the **stacked** data (to save it and work on it, for instance if I start from a table in excel). It was possible on Rawgraphs v1

**Comment by mikima** [comment]
Added the button "copy to colipboard"
