### ISSUE TITLE
Accept strings for X axis of Line chart

### ISSUE THREAD

**Issue by knutwannheden** [rawgraphs/rawgraphs-app#244]
**In which part of the interface would this feature applies?**

[ ] 1. Load your data
[ ] 2. Choose a chart
[x] 3. Mapping
[ ] 4. Customize
[ ] 5. Export

**Is your feature request related to a problem? Please describe.**
In my data set I have two text columns and one number column. I would like to map one of the text columns to the X axis and the number column to the Y axis, while the second text column identifies the data points for one particular line.

**Describe the solution you'd like**
When selecting a text column as the X axis I would expect there to be evenly spaced labels for the distinct values in the text column (ordered alphanumerically).

**Describe alternatives you've considered**

**Additional context**
This is for instance something that works out of the box in [Falcon SQL Client](https://github.com/plotly/falcon). Here is what it would look like there for example:

![image](https://user-images.githubusercontent.com/408765/109299447-65b6a300-7835-11eb-8087-68c8a936b36a.png)

**Comment by mikima** [comment]
Hi @knutwannheden in line charts we forced data type to be number or date, since the ordering of strings would influence a lot the reading.
If the strings represent dates, I suggest you to convert them in an ISO format so they can be parsed by RAWGraphs

**Comment by knutwannheden** [comment]
OK. In Falcon SQL Client (and thus Plotly I suppose), the ordering is derived from the ordering given by the data.

In the example graph I have provided, I could of course assign a number to the values on the X axis (I would have to assign consecutive numbers to get the ticks evenly spaced), but I would really prefer to be able to have text values, since the numbers wouldn't really mean anything to the reader.
