### ISSUE TITLE
Decimal separators not working if changed to comma

### ISSUE THREAD

**Issue by FabioLana542** [rawgraphs/rawgraphs-app#245]
**RAWGraphs Version**

RAWGraphs 2.0 beta

**Web browser and version**

Google Chrome v. 90.0.4430.6

**Operating System**

Windows 10

**Steps to reproduce this**

I'm Italian and my csv file have 3 columns: Data, Temperatura, Umidita
Original fields format:
- Data: 2020-10-24 01:39:58
- Temperatura: 25,25
- Umidita: 63,3

I had to change the orginal date&timestamp in a supported one, plus the "," decimal separator in the english one "." to make a Line Graph. 
I tried to change them with the parsing options without success.
[Temp al 30112020_3.zip](https://github.com/rawgraphs/rawgraphs-app/files/6054573/Temp.al.30112020_3.zip)

**Project file**

**Additional context**

**Comment by mikima** [comment]
Thank you. It is actually a bug, even changing the decimal separator in the interface the columns are not correctly parsed:
<img width="1427" alt="Screenshot 2021-02-27 at 16 45 20" src="https://user-images.githubusercontent.com/907536/109392275-8822ec00-791b-11eb-9d4d-624d2dba54b8.png">

Attaching here the project file using @FabioLana542 data

[linechart-temperature.rawgraphs.zip](https://github.com/rawgraphs/rawgraphs-app/files/6054819/linechart-temperature.rawgraphs.zip)

**Comment by mikima** [comment]
it seems working on `dev`. attached a working project. Will be publicly available when we release the new version.

[linechart-temperature-fixed.rawgraphs.zip](https://github.com/rawgraphs/rawgraphs-app/files/6109832/linechart-temperature-fixed.rawgraphs.zip)

**Comment by FabioLana542** [comment]
Great.
Thank you.

Fabio

Il mar 9 mar 2021, 17:10 mikima <notifications@github.com> ha scritto:
