### ISSUE TITLE
Bump chart 

### ISSUE THREAD

**Issue by angelesbri1s** [rawgraphs/rawgraphs-app#246]
Hola hola!
**In which chart does the bug happen?**
- Bump chart 

**Web browser and version**
Brave Version 1.20.110 Chromium: 88.0.4324.192 (Official Build) (x86_64) 
and 
Chrome Version 88.0.4324.192 (Official Build) (x86_64)

**Operating System**
MacOSX Mojave 10.14.6

**Steps to reproduce this**
1. use sample database US elections
2. choose bump chart
3. drag and drop "year" into X axis
4. qui vine un messagio in rosso che dice "chart error. V is not a function"

**Additional context**
salutiiiiiii

**Comment by giorgiouboldi** [comment]
ok. One way to fix it is to force the data type to year and set it to YYYY. 

@mikima we should make it possible to use numbers like for the streamgraph or not?

Also, let's not use sample datasets that need data type transformations.
