### ISSUE TITLE
downloading .rawgraphs format

### ISSUE THREAD

**Issue by angelesbri1s** [rawgraphs/rawgraphs-app#251]
**RAWGraphs Version**
2.0 beta

**Web browser and version**
Brave Version 1.20.110 Chromium: 88.0.4324.192 (Official Build) (x86_64)
Chrome Version 88.0.4324.192 (Official Build) (x86_64)

**Operating System**
MacOSX 10.14.6 

**Steps to reproduce this**
- make a chart
- customize it
- download as .rawgraphs project
- my browser directly downloads in my pre-defined download location into .json format. The setup of my download with Brave browser is > location: downloads folder; inactivate: "Ask where to save each file before downloading"
- I can't open the project back in RAWGraphs (using "open your project" option)

**Project file**

**Additional context**
when browsers directly download into a predefined location, they change the .rawgraphs into .json. 
For Brave, the setup should be "Ask where to save each file before downloading", downloading as "all files" and then adding the .rawgraphs extension. 
Maybe many other RAWGraphs users will encounter this problem

**Comment by uf0** [comment]
Can't reproduce on MacOS 10.15.7

Needs deeper investigation
