### ISSUE TITLE
API call to translate .rawgraph into .jpeg/.png/etc

### ISSUE THREAD

**Issue by cuddihyge** [rawgraphs/rawgraphs-app#253]
(I've made a good-faith, hour+ attempt to search through docs and hope this question is reasonable)

Goal:  translate a .rawgraph file into a rendered graph file programatically.

Is there a REST-like call to the server, or do I need to use the code.

I couldn't find any docs on this in Wiki (not enough context to understand the API section).

**Comment by bianchimro** [comment]
Hi @cuddihyge your question is reasonable :)

We're publishing the rawgraphs-core (the library used by rawgraphs app) code and docs in the next weeks, and we'll explain in detail the process of rendering a rawgraphs chart from your javascript code (also from a project).
Here you can see an early preview of the API usage for this purpose:

https://observablehq.com/@bianchimro/test-rawgraphs

but keep in mind that the api is not totally stable and it could slightly change before the public release.


Also note that the example I linked lives in observablehq environment .. so the syntax is not "vanilla" javascript.

**Comment by bianchimro** [comment]
Hi @cuddihyge, we just released the [rawgraphs-core](https://github.com/rawgraphs/rawgraphs-core) library.
The api is not 100% stable and docs not 100% complete, but you should find all the information needed to perform your task, the example I linked in the previous comment is still a valid example.
