### ISSUE TITLE
Gantt chart missing in v2

### ISSUE THREAD

**Issue by segmentseth** [rawgraphs/rawgraphs-app#254]
**RAWGraphs Version**
2

**Web browser and version**
n/a

**Operating System**
n/a

**Steps to reproduce this**
load data

**Project file**
n/a

**Additional context**
It looks like the Gantt chart option is missing from the v2 interface.  Is that by design?

**Comment by mikima** [comment]
GANTT charts will be added in the next weeks.

For now you can use the old version at https://old.rawgraphs.io/
