### ISSUE TITLE
What happened to Voronoi Tessellation?

### ISSUE THREAD

**Issue by vizualism** [rawgraphs/rawgraphs-app#259]
**In which part of the interface would this feature applies?**

[ ] 1. Load your data
[ x] 2. Choose a chart
[ ] 3. Mapping
[ ] 4. Customize
[ ] 5. Export

**Is your feature request related to a problem? Please describe.**
Awesome update to 2.0. But what happened to Voronoi Tessellation? 

**Describe the solution you'd like**
Could you please implement also that chart in your newest update?

**Describe alternatives you've considered**
The chart works fine in 1.1, but how long are you expected to keep that one running?

**Additional context**
****

**Comment by mikima** [comment]
The chart is in the roadmap, it will be added in the near future

**Comment by mikima** [comment]
added with [97948c0](https://github.com/rawgraphs/rawgraphs-charts/commit/97948c0730b51005d55adb5be80a45e8a4927363). will be visible in the new release.
