### ISSUE TITLE
Sorting column data in preview table doesn't not affect the real dataset ordering

### ISSUE THREAD

**Issue by CRC-PSV** [rawgraphs/rawgraphs-app#261]
- Treemap diagram

**RAWGraphs Version**
2.0beta

**Web browser and version**
Firefox 86.0

**Operating System**
MacOs catalina 10.7

**Steps to reproduce this**
I started a project with a specific data ordering, then produced a Treemap. Looks great, except that the higher categories are sorted in a particular order, as they were entered, though I need them ordered by alphabetical order
When I scroll up to the "upload your data" section, I can reorder my data in the right alphabetical order.
But then there is no change in the chart.
Shouldn't changing the orders in the data column affect the ordering of the boxes in a treemap? Otherwise, what's the use?

If I use Rawgraph1.0, I can upload the data, stack it, copy it, paste it under excel, sort it (in the right way), check it, then copy it to Rawgraph2.0, and bingo, the Treemap looks different.

I enclose Rawgraphs project files.

It would be good to be able to update a Treemap graph (from a saved Rawgraph project) by using the data reordering functions.

Or am I missing something?

Thank you!

[Archive.zip](https://github.com/rawgraphs/rawgraphs-app/files/6111991/Archive.zip)

**Comment by mikima** [comment]
Hi @cmalat01, you're right - ordering in the data preview doesn't really affect the data order.
The only way, is to order int in a spreadsheet software, but as you noted if you stack the data at the moment is impossible to re-export it.

So at the moment the only way to do it is through the old raw as you did.

We are already working on the topic to understand which behaviour is the most suitable:
* make the preview ordering effective on data
* allow to export data after unstacking it

**Comment by cmalat01** [comment]
Thank you! Keep up the good work!

**Comment by mikima** [comment]
Now it's possible to copy/paste stacked data
