### ISSUE TITLE
Label customization in circle pack charts

### ISSUE THREAD

**Issue by avfac** [rawgraphs/rawgraphs-app#267]
**In which part of the interface would this feature applies?**

[ ] 1. Load your data
[ ] 2. Choose a chart
[ ] 3. Mapping
[x] 4. Customize
[ ] 5. Export

**Is your feature request related to a problem? Please describe.**
I was hoping that the new release would solve the issue of lack of customization of labels. When using the circle pack charts, I still cannot change the font size of the labels in the circles or change them so that they fit withiin the circle. At the moment they are coming out of the circle for circles that are small. It would be a huge improvement to be able to increase the font size of labels and where in the circle they sit.

**Describe the solution you'd like**
 It would be a huge improvement to be able to increase the font size of labels, which is very small, and where in the circle they sit (ie, in one line, two lines etc, so that they do not spill over outside the circle).

**Describe alternatives you've considered**

**Additional context**

**Comment by uf0** [comment]
see #237
