### ISSUE TITLE
How to use rawgraphs in my django dashborad

### ISSUE THREAD

**Issue by MrPallaBall** [rawgraphs/rawgraphs-app#276]
How I can use rawgraphs in my django project?

I can create JSON data or CSV Data automatically, but I would like to use rawgraphs to create charts as like as a user want.

**Comment by bianchimro** [comment]
Hi @MrPallaBall, if you want to integrate with a django project, I suggest to take a look at our [rawgraphs-core](https://rawgraphs.io/rawgraphs-core) library.
We cannot provide specific information about django integration, but you can find some information about creating charts from your javascript code.
