### ISSUE TITLE
(Failed to compile) Module not found: 

### ISSUE THREAD

**Issue by makhas** [rawgraphs/rawgraphs-app#293]
**Web browser and version**
Chrome 90.0.4430.212 (Official Build) (64-bit) (cohort: Stable)

**Operating System**
 Windows 10 

**Steps to reproduce this**
1. clone repository
2. run npm install to download relevant dependencies
3. npm run start
4. Failure to Compile occurs

**Additional context**
![image](https://user-images.githubusercontent.com/50090981/119697231-fb0a0900-be1d-11eb-9c94-18942e5113c5.png)

**Comment by makhas** [comment]
A quickfix:

Go into node_modules/react-data-grid/ and create a new folder 'dist' containing 'react-data-grid.css'. I left the css file empty, and the site locally compiled sucessfully! Hopefully these are just missing files that can be added to the repo, and it seems like they aren't necessary for the most part.

**Comment by osioalberto** [comment]
Mixing package manager is not advisable and should be avoided. The issue you are experiencing depends on you using `npm`, while we use `yarn` to manage packages: hence, we provide the `yarn.lock` and not the `package-lock.json`. Switching to yarn as stated in the readme fixes the issue.

**Comment by mikima** [comment]
@makhas as suggested by @osioalberto use yarn (and not npm) to install dependencies. Here the link to the install instruction: https://github.com/rawgraphs/rawgraphs-app#instructions-mac-os

**Comment by robson-koji** [comment]
Only for the records, I had the same problem here even using yarn. @makhas log messages show that he is running Windows. I am using Linux. Maybe npm/yarn repos are missing something.  Quickfix worked just fine!
