### ISSUE TITLE
The Alluvial digram is not accurate in interpretation

### ISSUE THREAD

**Issue by mfathi-abdallah** [rawgraphs/rawgraphs-app#305]
**In which chart does the bug happen?**

- Alluvial diagram

**Steps to reproduce this**

the diagram sometimes make interpretation of the inputs in a wrong way just if i changed the chart variables. I used one month ago and it was perfect.

**Project file**

**Additional context**

**Comment by mikima** [comment]
Could you please give an example, by uploading a `.rawgraphs`project example?

**Comment by mfathi-abdallah** [comment]
hi, 
Thanks for the reply. I am attaching raw data 

if you upload these data to rawgraphs>>> choose alluvial diagram >>> then go to chart variables >>> set publication year, sample and continent >> you will have a correct figure expressing/visualizing  the data. However, if you place the continent in the middle as variable, you will get wrong figure. I used the website two months ago and was good, so I guess some upgrades or changes happened leaded to this. 

hope I could give an understandable example with my limited knowledge.

cheers 


mo 

[Alluvial correaction_africa example.xlsx](https://github.com/rawgraphs/rawgraphs-app/files/6861999/Alluvial.correaction_africa.example.xlsx)

**Comment by mikima** [comment]
I tried with the dataset and i cannot see the error, below the visualisations I obtain. Maybe I'm missing it, could you show me the error?
![alluvial-continent-middle](https://user-images.githubusercontent.com/907536/127527418-9c8b8ef9-8678-41c5-92f7-30ef7c7b32e3.png)
![alluvial-continent-end](https://user-images.githubusercontent.com/907536/127527428-3853636c-e988-405d-975b-e677257c155a.png)

Attached here the project files:
[alluvial-africa-projects.zip](https://github.com/rawgraphs/rawgraphs-app/files/6901988/alluvial-africa-projects.zip)
