### ISSUE TITLE
Display the count of items which determines the size, e.g. in Circle Packing

### ISSUE THREAD

**Issue by GilShalit** [rawgraphs/rawgraphs-app#308]
I want to display the relative size of various combinations of attributes.  So for example if I have a table with people's names, genders and professions.  And I'm placing gender as the first dimension, professions as the second, and the same in labels.  I'm using genders for color and leaving Size empty.  I then get a nice hierarchy of circles for the different combinations.

It would be extremely helpful to have the count used for each circle to be also printed out.  So for the circle labeled 'Female / Politian' I would also get Count=732.

Does this make sense?  Am I missing something?

**Comment by mikima** [comment]
the label can only be displayed if a dimension is dragged onto the visual variable "labels".

the most simple solution is to add to your dataset a column filled with 1 values so you can use it as label.

See the attached .rawgraph project:
[circle-packing-amounts.rawgraphs.zip](https://github.com/rawgraphs/rawgraphs-app/files/6901939/circle-packing-amounts.rawgraphs.zip)

**Comment by GilShalit** [comment]
Cool, thanks!
