### ISSUE TITLE
How to create a Clustered Force Layout Chart?

### ISSUE THREAD

**Issue by RGologorsky** [rawgraphs/rawgraphs-app#309]
Hi, I would like to recreate the Clustered Force Layout chart at https://www.storybench.org/how-to-build-a-clustered-bubble-chart-without-javascript/.  This chart is in the examples of the front page. However when I load my data I don't see an option for creating this chart. Please advise. Thank you.

![image](https://user-images.githubusercontent.com/15915563/128407832-d15d38e6-b55d-4c58-aaeb-640fe8987fca.png)

**Comment by mikima** [comment]
Hello, that model was present in the previous version, but not added to the new one. Its development is not planned by the core maintainers.
You can anyway use a circular packing to achieve a similar result
