### ISSUE TITLE
Raw library (API)?

### ISSUE THREAD

**Issue by k3n** [rawgraphs/rawgraphs-app#31]
Put simply, this is a pretty awesome application. However, it seems like it's power is more in its abilities than as a stand-alone site -- at least that's where my interest lies.

I do realize that since the code is all here, one could pull out whatever's needed and form their own library to work with the code on a programmatic level, but I was curious if there was any intention of this being officially supported? E.g. install the Raw module, call some `importData(...)` method, apply mappings, set the rendering options, and then `saveAs("svg")` or similar?

Again, pretty impressive project, regardless!

**Comment by Vistritium** [comment]
+1, it would be useful.
