### ISSUE TITLE
Sort bars doesn't work

### ISSUE THREAD

**Issue by giorgiouboldi** [rawgraphs/rawgraphs-app#312]
**In which chart does the bug happen?**

- Bar chart

**RAWGraphs Version**

Can't find it

**Web browser and version**

Chrome Version 92.0.4515.159 (Official Build) (x86_64)

**Operating System**

MacOS Big Sur

**Steps to reproduce this**

I created a bar chart and when i tried to sort the bard by size the option didn't work.

**Comment by kischacht** [comment]
noticing the same issue.

**RAWGraphs Version:** 2.0

**Web browsers:**
Chrome Version Version 93.0.4577.82 (Official Build) (x86_64)
Firefox Version 78.14.0esr (64-Bit)

**Operating system:** MacOS Mojave 10.14.6

**Comment by mikima** [comment]
duplicated of https://github.com/rawgraphs/rawgraphs-charts/issues/93

please comment there for updates
