### ISSUE TITLE
Sorting by "Original" not working in Bar Chart

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [rawgraphs/rawgraphs-app#314]
**In which chart does the bug happen?**

- Bar chart

(It does NOT happen in box plot, multi-set, or stacked bar)

**RAWGraphs Version**

2.0 Beta (there was no version info in the top-right of the interface)

![image](https://user-images.githubusercontent.com/2776014/134790321-4347fd8d-51b4-4f73-8241-fccaa426af88.png)

**Web browser and version**

Replicates on

- Chromium 89.0.4389.114
- Firefox 91.0

I have not yet been unable to replicate this bug

**Operating System**

Windows 10.0.18363

**Steps to reproduce this**

1. Paste the following data:  
   ```tsv
   FieldName,n,FieldValue
   One,91859,20.3
   Two,166070,17.9
   Three,110440,10.8
   Four,62503,7.8
   FourAndAHalf,14733,11.1
   Five,9975,14.6
   NegativeOne,70064,23.7
   ```
2. Choose `Bar chart`
3. Assign `FieldName` to `Bars` and `FieldValue:Sum` to `Size`
4. Under `Customize`\>`Chart`\>`Sort bars by`, toggle it around between the various settings
5. Observe as the bar ordering does not change at all

**Project file**

> We don't support that file type. Try again with a GIF, JPEG, JPG, MOV, MP4, PNG, CSV, DOCX, FODG, FODP, FODS, FODT, GZ, LOG, MD, ODF, ODG, ODP, ODS, PDF, PPTX, TXT, XLS, XLSX, or ZIP.

**Additional context**

![image](https://user-images.githubusercontent.com/2776014/134790307-7048294e-155c-4fc4-8d7e-127bd521fade.png)

**Comment by mikima** [comment]
duplicated of https://github.com/rawgraphs/rawgraphs-charts/issues/93

please comment there for updates
