### ISSUE TITLE
Bar chart > Chart > Sort bars by not working

### ISSUE THREAD

**Issue by tomflendrig** [rawgraphs/rawgraphs-app#320]
The 'Sort bars by' function doesn't work. The bars stay in the default order.

I'm using a macbook with Google Chrome.
Me and my professor looked if I did something wrong but it doesn't seem so

Added a screen recording of the issue:

https://user-images.githubusercontent.com/28000005/135624268-17244c50-a67d-41f2-b86e-237d75c5a388.mp4

.

**Comment by mikima** [comment]
Hi @tomflendrig thank you. The issues has been fixed in https://github.com/rawgraphs/rawgraphs-charts/issues/93.

It will be visible with the release of next RAWGraphs version.
