### ISSUE TITLE
Decimal values with commas

### ISSUE THREAD

**Issue by mikima** [rawgraphs/rawgraphs-app#35]
Raw identifies the decimal part only if separated by point "."
When the decimal part is marked by comma, Raw discard it, keeping the integer number.
In my opinion or Raw parses it as float, keeping the decimal, or it stores values as strings.
This is because keeping just the integer part can bring to conceptual errors: the user is sure that values are correctly parsed while they are not.

**Comment by PawandeepKaur** [comment]
I solved this issue by using regex after line 55

if(raw.typeOf(match) == "Number" && match.lastIndexOf(',') )  { match=match.replace( /\,/ , "." );}

It worked for me,,
