### ISSUE TITLE
button "Add your chart!" should become "Load a chart!"

### ISSUE THREAD

**Issue by iosonosempreio** [rawgraphs/rawgraphs-app#376]
**In which part of the interface would this feature applies?**

[ ] 1. Load your data
[x] 2. Choose a chart
[ ] 3. Mapping
[ ] 4. Customize
[ ] 5. Export

**Is your feature request related to a problem? Please describe.**
The button "Add your chart!" should become "Load a chart!"

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
None.

**Additional context**
Additionally we may consider of using the phrase "visualization template" instead of "chart"

**Comment by bianchimro** [comment]
Paritially done: now the button label is "Load custom chart" but the loading modal header is "Add a new custom chart"
