### ISSUE TITLE
Issue in Mapping Interface - Click and drag feature not working

### ISSUE THREAD

**Issue by daigokamada** [rawgraphs/rawgraphs-app#377]
**Description**
Hello, to whom it may cocern! Working on a data visualization project, I uploaded the dataset and select the Line chart option. However, in the mapping section I cannot click and drag the columns (variables) to the respective sections of the graph (X-Axis, Y-axis, Series, etc.). I never have encountered this issue in other websites/webpages. 

I am using an Android tablet (Samsung S7), and tried it with three different browsers (Chrome, Samsung Internet, Opera), and using the Mobile and Desktop site options. The click and drag do not work in version 2.0. I realized that going to the Rawgraph v.1 does work. However, much of the available chart types and options are lost.

I've checked the update of the applications through Google Play, and they are all updated. Please, if anyone can help in a promptly manner, I would be very grateful. I have a project that is Data Viz-related that I need to finish ASAP. 

**RAWGraphs Version**
2.0

**Web browser and version**
Chrome (v.111.0.5563.116), Opera (v.74.1.3922.71199), Samsung Internet (v.20.0.3.10) 

**Operating System**
Android 13

**Steps to reproduce this**
Copy paste edited dataset (for ex. Happiness Index, using only years from 2017 to 2019), select Line Chart, and try to click and drag the variables to the desired areas of the graph (e.g. Year to X-Axis, Positive Effect to Y-Axis)

**Comment by giorgiouboldi** [comment]
Hi, RAWGraphs has never been conceived specifically for touch screens. We will look into the issue but it's not a priority at the moment.
