### ISSUE TITLE
The line chart is adding commas and dot to the input values in the x axis

### ISSUE THREAD

**Issue by yvelice** [rawgraphs/rawgraphs-app#393]
**In which chart does the bug happen?**

- Alluvial diagram
- Arc Diagram
- Bar chart
- Stacked bar chart
- Multiset bar chart
- Beeswarm plot
- Boxplot
- Bump chart
- Circle Packing
- Contour Plot
- Circular dendrogram
- Linear Dendrogram
- Hexagonal Binning
- Line chart
- Matrix plot
- Radar chart
- Sankey diagram
- Streamgraph
- Sunburst diagram
- Treemap diagram
- Violin plot

**RAWGraphs Version**

**Web browser and version**

**Operating System**

**Steps to reproduce this**

**Project file**

**Additional context**

**Comment by yvelice** [comment]
Bar chart

**Comment by mikima** [comment]
could you provide an example with screenshoot?
