### ISSUE TITLE
Presentation of the graphs

### ISSUE THREAD

**Issue by gavigna** [rawgraphs/rawgraphs-app#398]
**In which part of the interface would this feature applies?**

[ ] 1. Load your data
[ ] 2. Choose a chart
[ ] 3. Mapping
[x] 4. Customize
[ ] 5. Export

**Is your feature request related to a problem? Please describe.**
I produced a very nice Alluvial diagram, but it seems it's impossible to change the font size of the descriptions, title of steps, whatever.

**Describe the solution you'd like**
I would appreciate the possibility to change the font size 

**Describe alternatives you've considered**

**Additional context**

**Comment by mikima** [comment]
Thank you for the feedback, change of font family / size is not planned at the moment
