### ISSUE TITLE
Image Quality is very poor

### ISSUE THREAD

**Issue by MSPeelam** [rawgraphs/rawgraphs-app#407]
**In which part of the interface would this feature applies?**

[ ] 1. Load your data
[ ] 2. Choose a chart
[ ] 3. Mapping
[ ] 4. Customize
[ ] 5. Export

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MSPeelam** [comment]
After everything image quality is very bad kindly add new feature for image quality

**Comment by mikima** [comment]
RAWGraphs is intended mainly for the generation of SVG iamges.
The suggestion is to downlaod the chart in SVG and then rasterize it at the resolution you prefer
