### ISSUE TITLE
Correctness of convex hull chart

### ISSUE THREAD

**Issue by Ehti1Indo** [rawgraphs/rawgraphs-app#411]
Hi there!
**In which chart does the bug happen?**           **- Convex Hull**

**RAWGraphs Version**                   **2.0**

**Web browser and version**

**129.0.6668.59 (Official Build) (64-bit) (cohort: Stable)** 

**Operating System**

**Steps to reproduce this**

**Project file**

**Additional context**

<img width="587" alt="image" src="https://github.com/user-attachments/assets/5479dd86-77fb-4687-ba53-0fb8879c84d0">

 the issue is that at one point the graph is not as per the point highlighted in the image attached.

**Comment by mikima** [comment]
convex hull joins the points needed to create a convex area that contains all the points of the same category.
This is the expected behaviour.

At the moment RAWGraphs is not able to handle concave areas
