### ISSUE TITLE
Title tag in many elements as possibile

### ISSUE THREAD

**Issue by jenkin** [rawgraphs/rawgraphs-app#69]
Labels are often useless because of their numbers. In some viz it is possible to hide them (ie. circle packing), but not in all (ie. clustered force layout). Also without labels, it could be useful identify each element, for example using tooltip generated by title tags. So I suggest to add a title tag to _every_ element (circle, bar, ...) when possibile and useful. Thanks! :)

**Comment by mikima** [comment]
We updated some of the visual models in this direction. We will keep this issue open until we will update all of them.
